#!/usr/bin/env sh

lilypond aristeia2.ly
lilypond nonagram.ly

pdfcrop --margins 10 nonagram.pdf

xelatex titlepage.tex
xelatex perf_notes.tex

# lilypond score.ly
# pdftk score.pdf cat 1 output score-p1.pdf
# pdfcrop --margins "10 -280 -50 -300" score-p1.pdf score-page1-crop.pdf

# xelatex test.tex
# xelatex titlepage.tex

pdftk titlepage.pdf perf_notes.pdf aristeia2.pdf cat output aristeia.pdf && open aristeia.pdf




