#!/usr/bin/env sh

lilypond aristeia2.ly
lilypond nonagram.ly
lilypond tuplets.ly

pdfcrop --margins "10 10 10 -210" nonagram.pdf instruments-cropped.pdf
pdfcrop --margins "10 -210 10 10" nonagram.pdf tuplets-cropped.pdf
pdfcrop --margins "-30 10 -250 -796" tuplets.pdf tuplet1.pdf
pdfcrop --margins "-120 10 -150 -796" tuplets.pdf tuplet2.pdf
pdfcrop --margins "8 5 8 0" tuplet1.pdf tuplet1.pdf
pdfcrop --margins "8 5 8 0" tuplet2.pdf tuplet2.pdf

xelatex titlepage.tex
xelatex perf_notes.tex

pdftk titlepage.pdf perf_notes.pdf aristeia2.pdf cat output aristeia.pdf && open aristeia.pdf




